REM ***********************************************************************************************
REM *                              WARNING: DO NOT EDIT THIS FILE                                 *
REM *                                                                                             *
REM * This file is generated by SUSHI. Any edits you make to this file will be overwritten.       *
REM ***********************************************************************************************

@ECHO OFF
CALL ./_genonce.bat -watch