#!/bin/bash

# *************************************************************************************************
# *                               WARNING: DO NOT EDIT THIS FILE                                  *
# *                                                                                               *
# * This file is generated by SUSHI. Any edits you make to this file will be overwritten.         *
# *************************************************************************************************

./_genonce.sh -watch